yorkxin/copy-as-markdown

- src/manifest.json
All functionality seems to work fine with the activeTab permission instead of the URL-based permissions, and avoids scary warnings about "access all your data" when installing. (Closes #14)
"tabs" is still needed to do the multi-tab link lists.
> Switch to activeTab permission.

- src-fx/package.json
Tested with Firefox Developer Edition with Multiprocess enabled
Closes #43
> Enable multiprocess mode

- src/background/context-menus.js
Chrome & Firefox will merge them into a single parent when there are multiple items
Solves #59 
Optional:
> Don't use parent context menu

- src/background/index.js
The previous implementation will register listeners _only_ on installed or updated.
This patch ensures that every time the background is loaded, the listeners are registered properly.
Optional:
> Listeners should be registered every time the background page is loaded

- src/manifest.json
Chrome Background Page must be running all the time, otherwise we cannot re-register listeners.
There must be something I don't understand in the doc https://developer.chrome.com/extensions/background_pages
Optional:
> Disable Chrome Event Page

- src/background/index.js
The old code was for Event Page model.
Since I removed Event Page and migrated to persistent Background Page #75, the context menus must be created when background page is loaded, not `onInstalled`.
Optional:
> Persistent context menus

- src/background/badge.js
- src/background/browser-as-markdown.js
- src/background/context-menus.js
- src/background/index.js
- src/background/message-handler.js
- src/manifest.json
- src/ui/popup.js
Optionally request for controversial `tabs` permission when first click.
Note that it's still controversial that it grants `tabs` permission forever.
Optional:
> Utilize optional permissions

- src/background/context-menus.js
- src/manifest.json
Chrome web store still rejects the extension due to extensive permissions. Let's try moving `activeTab` to optional permission, only for Firefox.
> Your product violates the "Use of Permissions" section of the policy, which requires that you:
> 
> - Request access to the narrowest permissions necessary to implement your product’s features or services.
> - If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
> - Don't attempt to "future proof" your product by requesting a permission that might benefit services or features that have not yet been implemented.
Optional:
> Request activeTab permission on demand (for Firefox)

- src/background/browser-as-markdown.js
- src/background/context-menus.js
- src/manifest.json
- src/ui/popup.js
Per [discussion](https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!msg/chromium-extensions/vUAxAWSD8fE/hwZRo8PCAgAJ) with Chrome Developer Support team, it is recommended not to include activeTab permission if not used (even if it's for Firefox compatibility).
Optional:
> Remove unnecessary activeTab permission

- src/manifest.json
Add keybinding for selected tab operations
Optional:
> Add keybinding for selected tab operations

- firefox-mv2/background.html
- firefox-mv2/create-menus.js
- firefox-mv2/manifest.json
Solves #107 
`chrome.runtime.onInstalled` is not called when Firefox restarted. This behavior is inconsistent with Chrome.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1567467
Followup explores:  (not a release blocker)
- Confirm behavior on Firefox MV3
- Refactor code so that codes of menus creation are not copy-pasted.
- Consider introducing custom menu lifecycle manager like uBlock?
Optional:
> Workaround: Menus disappears on Firefox when restarted

- chrome/manifest.json
- src/iframe-copy.html
- src/iframe-copy.js
- src/lib/clipboard-access.js
It seems that injecting an iframe (an HTML page bundled in the extension) can work around Chrome's `document.execCommand` restriction. Not sure if this is a security hole though. At least it works on my machine.
(I am doubting the meaning of my life)
Optional:
>  Inject an iframe to perform copy on Chrome + Keyboard Shortcut 

- README.md
- firefox/background.html
- firefox/manifest.json
- package.json
Firefox 112 now supports ESM background script in MV3. This means that
1. The problem with contextMenu.create() not being called in chrome.runtime.onInstalled is gone.
2. No more background.html hack
See:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background
https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
> Attempt to solve the issue of context menu with MV3

- firefox/hacks.js
- firefox/manifest.json
- src/background.js
In Firefox, when context menus were created in MV3, they may disappear unintentionally, even after restart. This is due to a bug in Firefox [1].
This patch introduces a hack which removes and re-creates all the menus every 30 seconds.
[1]: https://discourse.mozilla.org/t/strange-mv3-behaviour-browser-runtime-oninstalled-event-and-menus-create/111208/7
Related: #109 
Optional:
> Hack: Periodically re-create context menus in Firefox

- src/lib/markdown.js
Change the unordered list bullet from asterisk (`*`) to dash (`-`).
Why?
1. Prettier formats Markdown with dashes, see https://github.com/prettier/prettier/issues/4251
2. [Logseq](https://github.com/logseq/logseq) also uses dashes for unordered lists. Pasting multiple links with asterisks is not recognized as a list by Logseq.
I'm aware that the specs allow both of them though:
- [Lists | Daring Fireball: Markdown Syntax Documentation](https://daringfireball.net/projects/markdown/syntax#list)
- [List items | CommonMark Spec](https://spec.commonmark.org/0.31.2/#list-items)
I use [Brave Browser](https://github.com/brave/brave-browser), which is Chromium-compatible and can use Chrome extensions.
So I only tested on this one.
Optional:
> Use dash for unordered lists

- firefox/hacks.js
- src/background.js
- src/lib/markdown.js
- src/lib/settings.js
- src/ui/options.html
- src/ui/options.js
- test/markdown.test.js
- New option: unordered list style (`-`, `*` or `+`). 
- Changed default style of unordered list to `-` as this is more common today. (See #126) 
Closes #98 
Optional:
> Allow choosing the style of unorderd list

- chrome/manifest.json
- firefox-mv2/manifest.json
- firefox/manifest.json
- src/background.js
- src/lib/markdown.js
- src/ui/popup.html
- test/markdown.test.js
- A new menu item to copy links of tabs as task list (GitHub Flavored Markdown) in the popup window.
- Keyboard Shortcut for task list copying.
Optional:
> Copy Links of Tabs as Task List

- .eslintrc.json
- chrome/manifest.json
- firefox-mv2/manifest.json
- firefox/manifest.json
- package-lock.json
- package.json
- src/background.js
- src/ui/about.md
- src/vendor/turndown.js
- test/frameset.html
- test/iframe.html
- test/qa.html
- A new context menu "Copy Selection as Markdown" that converts the selection on page as Markdown. Closes #82 
- A new keyboard shortcut item "Copy Selection as Markdown" that does the same thing above.
Optional:
> Feature: Copy page selection as Markdown

- src/background.js
- When copying selection as Markdown, modify the DOM tree so that `<a href>` and `<img src>` are all absolute URLs.
Closes #136 
Optional:
> Resolve absolute URLs when copying selection as Markdown

- firefox/create-menus.js
- src/background.js
- Firefox: Adds context menus to the tab bar. Because it makes sense to have Copy Tab(s) as Markdown when right-clicking on the tabs. This feature is Firefox-only because there is no such API on Chrome.
Optional:
> Firefox tabs context menu

- src/background.js
- src/lib/markdown.js
- src/lib/settings.js
- src/ui/options.html
- src/ui/options.js
- test/markdown.test.js
- Indentation of tab groups can be chosen between `spaces` and `tab`.
Resolves #142 
This feature is only available on Chrome/Chromium browsers. Firefox does not support Tab Groups.
Optional:
> Add an option for tab groups indentation

- chrome/manifest.json
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/BaseTest.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/OptionsPage.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/PermissionsPage.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/PermissionsPageTest.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/keyboardshortcut/TabExportingTest.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/keyboardshortcut/TabExportingWithGroupsTest.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/popup/PopupPage.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/popup/SimpleTest.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/popup/TabExportingTest.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/popup/TabExportingWithGroupsTest.java
- firefox/create-menus.js
- firefox/manifest.json
- src/background.js
- src/ui/options.html
- src/ui/options.js
- src/ui/permissions.html
- src/ui/permissions.js
- src/webext.js
* Making `tabs` and `tabGroups` optional permissions, so that users are informed when the extension requires additional permissions.
Related: #148 
Optional:
> Make tabs & tabGroups optional features

- firefox/create-menus.js
- Permissions dialog will appear when needed. Displaying the menu items also hints the user that such feature exists.
Optional:
> Restore context menus on tabs on Firefox

- .idea/jsLibraryMappings.xml
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/ContextMenuTest.java
- e2e/src/test/java/org/yorkxin/copyasmarkdown/e2e/keyboardshortcut/OnPageContentsTest.java
- e2e/support/pages/selection.html
- e2e/support/pages/selection.md
- src/background.js
Reported by https://github.com/yorkxin/copy-as-markdown/issues/163
When copying selection as Markdown, when there are embedded `<style>` and `<script>` tags in the dom, they should be removed from the result Markdown.
Optional:
> Remove embedded <style> and <script> tags

- .gitignore
- e2e_test/test_tabs_exporting.py
- firefox/manifest.json
- package-lock.json
- package.json
- scripts/debug.js
- src/background.js
- src/ui/options-permissions.html
Firefox supports tab groups API since 139, so it's time to turn on the tab groups feature in Copy as Markdown.
Optional:
> Firefox tab groups
